### ISSUE TITLE
hitsplats duplicating on uneven terrain OR large monsters

### ISSUE THREAD

**Issue by pock2793** [Extended-Hitsplats/extended-hitsplats#13] opened 2024-10-09 13:15 UTC
![image](https://github.com/user-attachments/assets/7def949f-27bb-4918-bd72-83a0c9e17807)
Also on things like scorpia and sometimes scorpions the hitsplats are misaligned

**Comment by YeahImRose** [comment] 2024-10-09 19:03
This is ultimately caused by the same thing as #12, so I'm going to close this for now.

**Closed as completed by YeahImRose** 2024-10-09 19:03 UTC
